---
title: Breast Cancer Proteomics Module
summary: Teaching module provided for the proteomics module. 
date: last-modified
author: Jacob Fredegaard Hansen, Lev Levitsky
hide:
  - navigation
---

<!--
# Put above to hide navigation (left), toc (right) or footer (bottom)

hide:
  - navigation 
  - toc
  - footer 

# You should hide the navigation if there are no subsections
# You should hide the Table of Contents if there are no important titles
-->

::: {.callout-note title="Section Overview"}

&#128368; **Total Time Estimation:** 8 hours

&#128172; **Learning Objectives:**
    
- Understand the workflow of the study.
- Retrieve and understand the study design and data from selected papers.
- Download and preprocess proteomics data using FragPipe.
- Set up and use FragPipe for TMT-labeled MS data analysis.
- Create accurate annotation files for data analysis.

:::   

# Welcome to the MS Data Analysis Module

In this module, you will learn about mass spectrometry (MS) data analysis using **Tandem Mass Tag (TMT)**–labeled data, focusing on insights from a breast cancer study. This module is designed to guide you through key stages of MS data analysis, from preparation to advanced analysis, ensuring accurate quantification of TMT-labeled data.

::: {.callout-note collapse="false"}
## Module Overview

The module is divided into three sections:

1. **Preliminary Work**
   - Explore the study design.
   - Retrieve relevant datasets.
   - Prepare essential files for downstream analysis.

2. **Analysis of MS Data Using FragPipe**
   - Data processing with FragPipe.
   - Set up workflows tailored to TMT-labeled samples.
   - Run MS data analysis.

3. **Data annotation with SDRF**
   - Get familiar with proteomics sample metadata.
   - Learn the structure of SDRF.
   - Annotate the study dataset.

4. **Data Screening, Multivariate Analysis, and Clustering**
   - Techniques for screening and organizing results.
   - Multi-variate analysis and clustering.
   - Reveal meaningful patterns in the dataset.
:::

By the end of this module, you will be equipped to manage TMT-labeled proteomics data and conduct detailed analyses crucial in clinical proteomics research.

**Let's get started!**



## Part 1: Preliminary work

{{< include ./Preliminarywork.qmd >}}


## Part 2: Analysis of MS Data Using FragPipe

{{< include ./AnalysisMSData_FragPipe.qmd >}}


## Part 3: Data annotation with SDRF

{{< include ./sdrf.qmd >}}


## Part 4: Data screening, multi-variate analysis and clustering {#sec-data-analysis}

{{< include ./DataScreening_Multivariate.qmd >}}


## Personal Details

+---------------+---------------------------------------------------------------------------------------------------+
|Name           | <textarea id="name" placeholder="Type your name here..." class="input-box"></textarea>            |
+---------------+---------------------------------------------------------------------------------------------------+
|Email          | <textarea id="email" placeholder="Type your email here..." class="input-box"></textarea>          |
+---------------+---------------------------------------------------------------------------------------------------+
|Course/Program | <textarea id="course" placeholder="Type your course/program here..." class="input-box"></textarea>|
+---------------+---------------------------------------------------------------------------------------------------+
|Date           | <textarea id="date" placeholder="Type the date here..." class="input-box"></textarea>             |
+---------------+---------------------------------------------------------------------------------------------------+

: Please fill in your information {.personal-details}

<button id="downloadBtn" class="download-button">Download Your Answers as PDF</button>

<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js"></script>

<script src="../javascripts/answers.js"/>

